# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('images', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ListForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemlist', models.CharField(max_length=1500)),
            ],
        ),
        migrations.AddField(
            model_name='forum',
            name='forum_items',
            field=models.ManyToManyField(to='forum.ListForum'),
        ),
    ]
